### ISSUE TITLE
Server crashs after removing a mod from modpack

### ISSUE THREAD

**Issue by poswar** [Cazsius/Spice-of-Life-Carrot-Edition#27]
Using 1.12 version. Steps to reproduce:

1) Eat some food from mod X
2) Shutdown the game and remove mod X from the modpack.
3) The following stacktrace will arrive:

Stacktrace:

java.lang.NullPointerException: Loading entity NBT
	at com.cazsius.solcarrot.capability.FoodInstance.equals(FoodInstance.java:47)
	at java.util.HashMap.putVal(HashMap.java:635)
	at java.util.HashMap.put(HashMap.java:612)
	at java.util.HashSet.add(HashSet.java:220)
	at com.cazsius.solcarrot.capability.FoodCapability.addFood(FoodCapability.java:27)
	at com.cazsius.solcarrot.capability.FoodCapability.deserializeNBT(FoodCapability.java:70)

**Comment by Cazsius** [comment]
What version of the mod are you using?

**Comment by poswar** [comment]
solcarrot-1.12.1-1.3.jar

I think that the issue is because the mod is trying to keep track of inexistent food in NBT player data.

The error shows just after the game reloads.

**Comment by Cazsius** [comment]
Interesting, I tested this and it was fine in dev env. I see the issue does exist though. Will investigate

**Comment by poswar** [comment]
nevermind... i could not replicate in a new clean environment with the same mod set.
